### ISSUE TITLE
https://github.com/CleverRaven/Cataclysm-DDA/pull/21538#issuecomment-319725794

### ISSUE THREAD

**Issue by AlecWhite** [DangerNoodle/Cataclysm-DDA#2]
I think what you are looking for is "burden of proof" fallacy.

Sorry to open an issue here, but I don't have any other way of contacting you @DangerNoodle

**Comment by DangerNoodle** [comment]
I see. Fallacy on my part, or that of Kevin?

**Comment by AlecWhite** [comment]
On the Kevin, he dismissed your argument without any proof, explanation or counter argument https://en.wikipedia.org/wiki/Burden_of_proof_(philosophy)

**Comment by DangerNoodle** [comment]
I see. That is consistent with my complaint towards him, yes.

**Comment by kevingranade** [comment]
The burden of proof is on the person making the PR, yes?
>  the one who makes the claim typically has a burden of proof to justify or substantiate that claim *especially when it challenges a perceived status quo*.

**Comment by DangerNoodle** [comment]
And I presented that argument. You were the one who, rather than responding to my reasoning, closed it with no explanation. Since I provided reasoning for changing it, the fallacy lies with you, given you did not address the point made. Even then, your point presented was already addressed, indicative of having not read the opening post, or of being unwilling to address a point that directly disputes the only reasoning you have provided this far.

This unfortunately has been consistent behavior on your part when responding to changes you disagree with, and is the reason for my anger earlier.

**Comment by kevingranade** [comment]
You have a very odd understanding of the principle.  Simply making an argument is not sufficient, as the PR author, *you* have the burden of *proof*.

If your change and your rationale aren't convincing, no refutation is actually necessary, explaining my rationale for rejection is a means to build understanding, not a requirement.  In this case, the case for the status quo had been made elsewhere already, so I didn't go to the trouble of making a case for it.  I might have dropped in a link to a previous discussion if I hadn't been on my phone at the time, but as it was it was too inconvinient.

Let make this perfectly clear, you are not *entitled* to an explanation, and your belief that you've 'won' an argument has no bearing on whether I accept a change or not.  This isn't a logic game or academic debate, your goal is to convince me that your change is a good idea, and the antagonistic way you've been approaching it is extremely counterproductive.

**Comment by DangerNoodle** [comment]
> This isn't a logic game or academic debate, your goal is to convince me that your change is a good idea, and the antagonistic way you've been approaching it is extremely counterproductive.

My apologies. Again, I acted out of anger. That said, you have a history of verbal abuse and a self-destructive attitude towards shutting down criticism, and I have found myself less willing to get involved in the project because of it.

@Coolthulhu is another example of someone that your actions have had an effect on, given the heated arguments I have witnessed between you two.
